apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "homeauto-api.fullname" . }}-config
  labels:
    {{ include "homeauto-api.labels" . | indent 4 | trim }}
data:
  config.yaml: |
    port: 80
    registerFunction: {{ .Values.registration.functionUrl }}
    clientId: {{ .Values.clientId }}
