apiVersion: v1
kind: Service
metadata:
  name: {{ template "homeauto-api.serviceName" . }}
  labels:
    {{ include "homeauto-api.labels" . | indent 4 | trim }}
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: {{ .Values.comms.nodePort }}
    name: restapi
  selector:
    {{ include "homeauto-api.selectors" . | indent 4 | trim }}
